[package]
name = "chat-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
dialoguer = "0.10.4"
reqwest = { version = "0.11", features = ["json","blocking"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"